name: CI

on:
  push:
    branches: [ '*' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-docker-plexanisync:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile: ./Docker/PlexAniSync/Dockerfile
      imagename: ${{ github.repository_owner }}/plexanisync
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          
  build-docker-tautulli:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile: ./Docker/Tautulli/Dockerfile
      imagename: ${{ github.repository_owner }}/tautulli-plexanisync
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
